[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Lucy <lucy@absolucy.moe>"]
edition = "2021"
license = "0BSD"
repository = "https://github.com/Absolucy/meowtonin"
rust-version = "1.81"
version = "0.2.0"

[workspace.dependencies]
libloading = "0.8"
